### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by mrbrianevans** [y21/tljs#1]
This looks like a very nice library with great performance compared to others, but I can only get it to work with nodejs.

Do you have plans to support browsers as well? It would be a very useful feature to me if it could run in browsers.

I am happy to help contribute to make it work in browsers, if you could give me some guidance.

Thanks, Brian

**Comment by y21** [comment]
What exactly doesn't work in the browser? I assume it's the function that attempts to load the WebAssembly binary, which you can override (by default, it tries to use `require('fs')` which of course does not exist in the browser). I'm not sure what the best way would be to expose the binary, but if you have a server that can serve it, then you can simply use something like `fetch` to fetch it in the browser:
(Edit: when installing the package via npm, the .wasm binary is located at `node_modules/@y21/tljs/node/dist/bindings.wasm`)
```js
const tljs = require('@y21/tljs');

// override the wasm loading function
tljs.setInitializerCallback(() => {
  return fetch('/tl.wasm').then(x => x.arrayBuffer()); // assuming `/tl.wasm` serves the binary.
});

const dom = await tljs.parse(`
    <!DOCTYPE html>
    <div>
        <p id="greeting">Hello World</p>
        <img id="img" src="image.png" />
    </div>
`);

console.log(dom.getElementById('img').asTag().attributes().get('src')); // image.png
```
I've been able to use this library in very restricted JS environments, but it does require some messing around, mostly to get wasm loading to work (all you need is an `ArrayBuffer` that contains the blob and WebAssembly support). If you're using webpack, you might also get an error because of the `require('fs')` line, but I'm not sure if there's a nice way to have it ignore that line.

(Also, thanks for opening this. I've been meaning to give this project more love, but I've mostly been working on the upstream Rust repo that this JavaScript library uses behind the scenes: [y21/tl](https://github.com/y21/tl). There's some things that could improve the performance quite a bit. I'd also like to rework the internals of this library a bit because it's quite error prone and makes adding features a little harder than I would like it to be).

**Comment by mrbrianevans** [comment]
Great, thanks for your response. I will try overriding the initializer callback and see if I can get it to work.

As far as I can tell, the way to load WASM depends on the bundler used and there doesn't seem to be an accepted standard across the board. I'm using Vite, which has its own way of loading WASM files, but this probably differs from other frameworks. If there was a consistent way of loading the binary, it could be included in this library, but I guess if its different for every bundler then its up to the user of the library.

My application needs to parse very large HTML documents in the browser, so the performance of this library would be great if I manage to get it working.

**Comment by mrbrianevans** [comment]
Okay I got it working. I used `fetch` to get the file as shown in your example, and it loaded the binary.
```js
import * as tljs from '@y21/tljs'
import wasmUrl from '@y21/tljs/node/dist/bindings.wasm?url'
tljs.setInitializerCallback(() =>  fetch(wasmUrl).then((res) => res.arrayBuffer()))
```
I also managed to use the Vite loading mechanism like this:
```js
import * as tljs from '@y21/tljs'
import initWasm from '@y21/tljs/node/dist/bindings.wasm'
initWasm({}).then((wasmExports) => tljs.setWasmExports(wasmExports))
```

I have noticed that the first time I parse HTML with the wasm module its slower than subsequent parses. This is even when setting the wasmExports directly. So if I understand it right, there shouldn't be any more to load on the first call than subsequent calls? I confirmed this by putting a `console.log` as the initiliasation callback function and it doesn't get called. Why might it be that the first time `parse` is called is slower than subsequent calls? And is there any way I can call this initial processing sooner (on page load for example), to avoid a slower parse of the first document?

**Comment by y21** [comment]
I think it makes sense to add something to the README that explains how to use this library in a browser (or other environments).
The long term plan for Node.js (and possibly Deno) is to implement bindings as a native Node module. Currently, there is quite a bit of overhead when calling into the WebAssembly/Rust function from JavaScript (namely the HTML string needs to be copied into WebAssembly memory). I believe with native modules we can directly get V8's string data pointer and pass it over to the Rust HTML parser, although I'm not exactly sure how well UTF-16 strings play together with a UTF-8 parser.

> As far as I can tell, the way to load WASM depends on the bundler used and there doesn't seem to be an accepted standard across the board. I'm using Vite, which has its own way of loading WASM files, but this probably differs from other frameworks. If there was a consistent way of loading the binary, it could be included in this library, but I guess if its different for every bundler then its up to the user of the library.

yep, I'm using this library in restricted environments with no network or filesystem access, so it's hard to find a module loading mechanism that works everywhere. Node.js is supported out of the box because that's fairly straight forward (the wasm binary is downloaded when installing the module, so we can just use `require('fs').readFile` to read it into an ArrayBuffer). In browsers, it gets more complicated because, as you said, everyone has their own setup, so I thought the best way is to expose a function that lets you override this loading mechanism. 

> I have noticed that the first time I parse HTML with the wasm module its slower than subsequent parses. This is even when setting the wasmExports directly. So if I understand it right, there shouldn't be any more to load on the first call than subsequent calls?

Yes, what you said seems right. Normally the very first call to `parse()` is expected to run much slower because that's when the module loading/instantiation etc. happens, but that should only happen *once*, and when wasm initialization happens before the first `parse()` call, then the first `parse()` call shouldn't be any slower. I'm not entirely sure what's happening either and I've noticed this before. You can see similar behavior if you comment out the entire function body so you end up with an empty async function:
```js
async function parse(input, options = {}) {}
```
Running a quick test script that reports the time it takes for the call to finish
```
0: 0.104ms
1: 0.013ms
2: 0.01ms
3: 0.005ms
4: 0.006ms
5: 0.011ms
6: 0.005ms
7: 0.005ms
8: 0.008ms
9: 0.008ms
```
The first line is consistently slower than subsequent calls.
It's possible that you are observing something internal to the JavaScript engine (i.e. V8 only starting to optimize the function once it realizes that it's a hot function, or something)...
I'm not sure if there's a better way to force the engine to optimize a function other than just calling `parse()` a bunch of times with small input.
